version: '3.8'
services:
  web:
    image: odoo:19.0
    depends_on:
      - db
    ports:
      - "8044:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - ODOO_MASTER_PASS=admin
    command: odoo --addons-path="/mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons"
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

volumes:
  odoo-web-data:
  odoo-db-data:
