import sys

print("=" * 60)
print("Searching for ALL website builder views that override the homepage...")
print("=" * 60)

# Find the original website.homepage view
homepage_views = env['ir.ui.view'].search([('key', '=', 'website.homepage')])
for hv in homepage_views:
    print(f"Found website.homepage: ID={hv.id}")
    
    # Find all child views of website.homepage
    child_views = env['ir.ui.view'].search([('inherit_id', '=', hv.id)])
    
    # Filter only those that are likely builder-generated 
    # (they either have NO key, or they start with 'website.' but are not standard modules)
    # The standard website module views usually have XML IDs in ir_model_data. 
    # Views created by builder usually don't have external IDs, or have autogenerated ones.
    
    for cv in child_views:
        # Check if it has an external ID
        ext_id = env['ir.model.data'].search([('model', '=', 'ir.ui.view'), ('res_id', '=', cv.id)])
        print(f"  Child View: ID={cv.id}, name={cv.name}, key={cv.key}, has_ext_id={bool(ext_id)}")
        
        # We want to delete views that are named 'Homepage' and have no external ID,
        # OR they are the corrupted ones.
        if cv.key == 'warehousepart.ran_ahlai_homepage':
            print(f"    -> Skipping our own template: {cv.key}")
            continue
            
        if not ext_id or not cv.key or cv.key.startswith('website.homepage_'):
            print(f"    -> DELETING builder view: ID={cv.id}")
            cv.unlink()

env.cr.commit()
print("Done!")
print("=" * 60)
sys.exit(0)
