# -*- coding: utf-8 -*-
{
    'name': 'ร้านอาหลั่ย — ระบบจัดการอะไหล่รถยนต์',
    'version': '19.0.2.0.0',
    'category': 'Inventory',
    'summary': 'ปรับแต่งระบบ Odoo มาตรฐานเพื่อใช้เป็นร้านขายอะไหล่รถยนต์',
    'author': 'Ran Ahlai',
    'depends': [
        'base', 
        'mail', 
        'product', 
        'uom',
        'point_of_sale', 
        'stock', 
        'purchase',
        'website_sale',
        'website',
        'hr',
        'pos_hr',
        'account',
        'l10n_th',
        'delivery'
    ],
    'data': [
        'data/warehouse_setup.xml',
        'security/spare_security.xml',
        'security/ir.model.access.csv',
        'views/menu_views.xml',
        'views/spare_quick_transfer_views.xml',
        'views/spare_part_views.xml',
        'views/backorder_report_views.xml',
        'views/homepage_category_views.xml',
        'views/website_templates.xml',
        'views/report_templates.xml',
        'data/ran_ahlai_master_data.xml',
        'data/ran_ahlai_master_data_bulk.xml',
        'data/uom_setup.xml',
        'data/demo_tracking_data.xml',
        'data/website_pages.xml',
        'data/flash_sale_data.xml',
        'views/stock_overview_views.xml',
        'data/pos_config_setup.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'warehousepart/static/src/scss/minimal_shop.scss',
            'warehousepart/static/src/js/website_frontend.js',
        ],
        'point_of_sale.assets_prod': [
            'warehousepart/static/src/xml/pos_receipt.xml',
            'warehousepart/static/src/js/pos_stock_hide.js',
            'warehousepart/static/src/xml/pos_enhancements.xml',
            'warehousepart/static/src/scss/pos_custom.scss',
        ],
    },
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
    'images': ['static/description/icon.png'],
}
